# Generated by Django 2.2.6 on 2019-11-19 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='DOR',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 8, 6, 16, 711329, tzinfo=utc)),
        ),
    ]
