# Generated by Django 2.2.6 on 2019-11-20 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0005_auto_20191119_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='DOR',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 28, 8, 239044, tzinfo=utc)),
        ),
    ]
