# Generated by Django 2.2.6 on 2019-11-20 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0007_auto_20191121_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
        migrations.AlterField(
            model_name='author',
            name='DOR',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 54, 49, 453934, tzinfo=utc)),
        ),
    ]
